workflows:
  android-workflow:
    name: Android Build
    environment:
      groups:
        - firebase_group  # Grupo com a variável GOOGLE_SERVICES_JSON
    scripts:
      - name: Setup Firebase Configuration
        script: |
          # Cria o arquivo google-services.json
          echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json
          
          # Verifica se o arquivo foi criado corretamente
          echo "Verificando arquivo google-services.json:"
          ls -la android/app/google-services.json
          echo "Conteúdo (primeiras linhas):"
          head -n 5 android/app/google-services.json
          
      - name: Get Flutter dependencies
        script: flutter pub get
          
      - name: Build Android APK
        script: flutter build apk --release
          
      - name: Build iOS app
        script: flutter build ios --release --no-codesign
