workflows:
  build_app:
    name: Build Android & iOS
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    triggering:
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set up Firebase config
        script: |
          echo $FIREBASE_CONFIG | base64 --decode > android/app/google-services.json
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --release
      - name: Build iOS app
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/iphoneos/*.app
