workflows:
  android-workflow:
    name: Android Build
    environment:
      vars:  # Usa variáveis diretamente (não grupos)
        GOOGLE_SERVICES_JSON: $GOOGLE_SERVICES_JSON  # Referencia a variável que você criou
    scripts:
      - name: Create google-services.json
        script: |
          # Garante que o diretório existe
          mkdir -p android/app/src/debug
          
          # Salva o JSON nos dois locais que o Gradle procura
          echo "$GOOGLE_SERVICES_JSON" > android/app/src/debug/google-services.json
          echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json
          
          # Verifica se os arquivos foram criados
          echo "Conteúdo de android/app/src/debug/google-services.json:"
          cat android/app/src/debug/google-services.json
          echo "Conteúdo de android/app/google-services.json:"
          cat android/app/google-services.json

      - name: Build Android
        script: |
          flutter pub get
          flutter build apk --debug
