workflows:
  build_app:
    name: Build Android & iOS
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      # A variável agora é lida da UI do Codemagic, não declarada aqui.
    triggering:
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set up Firebase config
        script: |
          # Este script agora é mais simples e robusto.
          # Ele pega a variável de ambiente GOOGLE_SERVICES_JSON e a salva no local correto.
          echo $GOOGLE_SERVICES_JSON > android/app/google-services.json
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --release
      - name: Build iOS app
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/iphoneos/*.app
