// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_mO5hzznVP-3rg7lRFxa2JzOwkpmo4Y8',
    appId: '1:633152736225:web:bcc165986f34af7a8860a0',
    messagingSenderId: '633152736225',
    projectId: 'meu-intercambio-app',
    authDomain: 'meu-intercambio-app.firebaseapp.com',
    storageBucket: 'meu-intercambio-app.firebasestorage.app',
    measurementId: 'G-MN3S52CPN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbZU0LOHy39BqhYE7q5boxpRXyAT6q5Yc',
    appId: '1:633152736225:android:c5fdd979f729543a8860a0',
    messagingSenderId: '633152736225',
    projectId: 'meu-intercambio-app',
    storageBucket: 'meu-intercambio-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-wvyTjUuYtWKe2afNRfXC3CE-7nxDIGM',
    appId: '1:633152736225:ios:8dafe13f2420c9dc8860a0',
    messagingSenderId: '633152736225',
    projectId: 'meu-intercambio-app',
    storageBucket: 'meu-intercambio-app.firebasestorage.app',
    iosBundleId: 'com.example.meuIntercambioPrototype',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-wvyTjUuYtWKe2afNRfXC3CE-7nxDIGM',
    appId: '1:633152736225:ios:8dafe13f2420c9dc8860a0',
    messagingSenderId: '633152736225',
    projectId: 'meu-intercambio-app',
    storageBucket: 'meu-intercambio-app.firebasestorage.app',
    iosBundleId: 'com.example.meuIntercambioPrototype',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_mO5hzznVP-3rg7lRFxa2JzOwkpmo4Y8',
    appId: '1:633152736225:web:e0cc8ce0a06a50308860a0',
    messagingSenderId: '633152736225',
    projectId: 'meu-intercambio-app',
    authDomain: 'meu-intercambio-app.firebaseapp.com',
    storageBucket: 'meu-intercambio-app.firebasestorage.app',
    measurementId: 'G-C6YE9QDSHM',
  );

}